---
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: add ubuntu to docker group
    user:
      name: centos
      groups: docker
      append: yes
  - name: copy docker-compose.yml
    copy:
      src: ./docker-compose.yml
      dest: ./docker-compose.yml
  - name: run docker-compose
    command: /usr/local/bin/docker-compose -d up
