---
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: add ubuntu to docker group
    user:
      name: centos
      groups: docker
      append: yes
  - name: install python-pip
    yum:
      name: python-pip
      state: present
  - name: install docker-py
    pip:
      name: docker-py
  - name: install Docker Compose
    pip:
      name: docker-compose
  - name: copy docker-compose.yml
    copy:
      src: ./docker-compose.yml
      dest: ./docker-compose.yml
  - name: run docker-compose
    environment:
      BUILD_TIMESTAMP: "{{ lookup('env', 'BUILD_TIMESTAMP') }}"
    docker_service:
      project_src: .
      state: present
      restarted: yes
